CREATE TABLE IF NOT EXISTS user (
  id        BIGINT       NOT NULL AUTO_INCREMENT,
  name      VARCHAR(100) NOT NULL,
  email     VARCHAR(100) NOT NULL,
  password  VARCHAR(100) NOT NULL,

  date_register DATETIME NOT NULL,
  
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;